---
abstract: 'BerkeleyDB driver for App::Milter::Limit'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100760'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Milter-Limit-Plugin-BerkeleyDB
requires:
  App::Milter::Limit::Log: 0
  App::Milter::Limit::Plugin: 0
  BerkeleyDB: 0
  Class::Accessor: 0
  Module::Signature: 0
  Socket: 0
  Test::More: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=App-Milter-Limit-Plugin-BerkeleyDB
  homepage: http://search.cpan.org/dist/App-Milter-Limit-Plugin-BerkeleyDB/
  repository: http://github.com/mschout/milter-limit-plugin-berkeleydb
version: 0.51
